name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DJANGO_SETTINGS_MODULE: tests.testapp.settings.settings
      PYTHONPATH: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage codecov pytest poetry
          pip install -r packages/requirements-dev.txt

      - name: Run tests with coverage
        run: pytest --cov=sage_newsletter --cov-report=xml

      - name: Run Tox tests
        run: tox

      - name: Run pre-commit hooks
        run: pre-commit run --all-files --config=.pre-commit-config-ci.yaml

      - name: Upload coverage to Codecov
        run: codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
